<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Plugin\SamplePayment\Service\Method\CreditCard' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Eccube\\Service\\Payment\\PaymentMethodInterface.php';
include_once $this->targetDirs[3].'\\app\\Plugin\\SamplePayment\\Service\\Method\\CreditCard.php';

return $this->services['Plugin\SamplePayment\Service\Method\CreditCard'] = new \Plugin\SamplePayment\Service\Method\CreditCard(${($_ = isset($this->services['Eccube\Repository\Master\OrderStatusRepository']) ? $this->services['Eccube\Repository\Master\OrderStatusRepository'] : $this->load('getOrderStatusRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Plugin\SamplePayment\Repository\PaymentStatusRepository']) ? $this->services['Plugin\SamplePayment\Repository\PaymentStatusRepository'] : $this->load('getPaymentStatusRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['eccube.purchase.flow.shopping']) ? $this->services['eccube.purchase.flow.shopping'] : $this->load('getEccube_Purchase_Flow_ShoppingService.php')) && false ?: '_'});
