<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\SamplePayment\Form\Extension\CreditCardExtention' shared autowired service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\FormTypeExtensionInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\AbstractTypeExtension.php';
include_once $this->targetDirs[3].'\\app\\Plugin\\SamplePayment\\Form\\Extension\\CreditCardExtention.php';

return $this->services['Plugin\SamplePayment\Form\Extension\CreditCardExtention'] = new \Plugin\SamplePayment\Form\Extension\CreditCardExtention(${($_ = isset($this->services['Eccube\Repository\PaymentRepository']) ? $this->services['Eccube\Repository\PaymentRepository'] : $this->load('getPaymentRepositoryService.php')) && false ?: '_'});
