<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\RelatedProduct4\RelatedProductEvent' shared autowired service.

include_once $this->targetDirs[3].'\\app\\Plugin\\RelatedProduct4\\RelatedProductEvent.php';

return $this->services['Plugin\RelatedProduct4\RelatedProductEvent'] = new \Plugin\RelatedProduct4\RelatedProductEvent();
