<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\SamplePayment\SamplePaymentEvent' shared autowired service.

include_once $this->targetDirs[3].'\\app\\Plugin\\SamplePayment\\SamplePaymentEvent.php';

return $this->services['Plugin\SamplePayment\SamplePaymentEvent'] = new \Plugin\SamplePayment\SamplePaymentEvent();
