<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\SamplePayment\Form\Type\Admin\SearchPaymentType' shared autowired service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\FormTypeInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\AbstractType.php';
include_once $this->targetDirs[3].'\\app\\Plugin\\SamplePayment\\Form\\Type\\Admin\\SearchPaymentType.php';

return $this->services['Plugin\SamplePayment\Form\Type\Admin\SearchPaymentType'] = new \Plugin\SamplePayment\Form\Type\Admin\SearchPaymentType();
