<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\SamplePayment\Form\Extension\CvsExtension' shared autowired service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\FormTypeExtensionInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\AbstractTypeExtension.php';
include_once $this->targetDirs[3].'\\app\\Plugin\\SamplePayment\\Form\\Extension\\CvsExtension.php';

return $this->services['Plugin\SamplePayment\Form\Extension\CvsExtension'] = new \Plugin\SamplePayment\Form\Extension\CvsExtension(${($_ = isset($this->services['Plugin\SamplePayment\Repository\CvsTypeRepository']) ? $this->services['Plugin\SamplePayment\Repository\CvsTypeRepository'] : $this->load('getCvsTypeRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Eccube\Repository\PaymentRepository']) ? $this->services['Eccube\Repository\PaymentRepository'] : $this->load('getPaymentRepositoryService.php')) && false ?: '_'});
