<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\EC4MOMO\Repository\MomoTransactionRepository' shared autowired service.

include_once $this->targetDirs[3].'\\app\\Plugin\\EC4MOMO\\Repository\\MomoTransactionRepository.php';

return $this->services['Plugin\EC4MOMO\Repository\MomoTransactionRepository'] = new \Plugin\EC4MOMO\Repository\MomoTransactionRepository(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'});
