<?php

namespace Proxies\__CG__\Plugin\SamplePayment\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Config extends \Plugin\SamplePayment\Entity\Config implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Plugin\\SamplePayment\\Entity\\Config' . "\0" . 'id', '' . "\0" . 'Plugin\\SamplePayment\\Entity\\Config' . "\0" . 'api_url', '' . "\0" . 'Plugin\\SamplePayment\\Entity\\Config' . "\0" . 'api_id', '' . "\0" . 'Plugin\\SamplePayment\\Entity\\Config' . "\0" . 'api_password'];
        }

        return ['__isInitialized__', '' . "\0" . 'Plugin\\SamplePayment\\Entity\\Config' . "\0" . 'id', '' . "\0" . 'Plugin\\SamplePayment\\Entity\\Config' . "\0" . 'api_url', '' . "\0" . 'Plugin\\SamplePayment\\Entity\\Config' . "\0" . 'api_id', '' . "\0" . 'Plugin\\SamplePayment\\Entity\\Config' . "\0" . 'api_password'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Config $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getApiUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApiUrl', []);

        return parent::getApiUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setApiUrl($api_url)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApiUrl', [$api_url]);

        return parent::setApiUrl($api_url);
    }

    /**
     * {@inheritDoc}
     */
    public function getApiId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApiId', []);

        return parent::getApiId();
    }

    /**
     * {@inheritDoc}
     */
    public function setApiId($api_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApiId', [$api_id]);

        return parent::setApiId($api_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getApiPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApiPassword', []);

        return parent::getApiPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setApiPassword($api_password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApiPassword', [$api_password]);

        return parent::setApiPassword($api_password);
    }

}
